'use client';
import { useEffect, useState } from 'react';
import { Radar, ShieldCheck, ExternalLink, Activity, ArrowUpRight } from 'lucide-react';
import Explorer from '../components/Explorer';
import AdminDashboard from '../components/AdminDashboard';
type View = 'explore' | 'compare' | 'crawler' | 'dashboard';
export default function Home() {
  const [view, setView] = useState<View | null>(null);
  useEffect(() => { const path = window.location.pathname.replace(/\/$/, ''); setView(path === '/compare' ? 'compare' : path === '/dashboard' ? 'dashboard' : path === '/crawler' ? 'crawler' : 'explore'); }, []);
  return <><header className="header"><div className="header-inner"><a className="brand" href="/" aria-label="Exam Radar 首頁"><span className="brand-icon"><Radar size={25} /></span>EXAM<span>RADAR</span></a><nav aria-label="主要導覽">{[['explore','/','探索段考'],['compare','/compare/','跨校比較'],['crawler','/crawler/','關於計畫']].map(([key, href, label]) => <a key={key} href={href} className={view === key ? 'active' : ''} aria-current={view === key ? 'page' : undefined}>{label}</a>)}</nav><a className="admin-link" href="/dashboard/">管理控制台 <ArrowUpRight size={15} /></a></div></header><main>{view === null ? <p className="loading" role="status">載入 Exam Radar…</p> : view === 'explore' || view === 'compare' ? <Explorer key={view} compare={view === 'compare'} /> : view === 'dashboard' ? <AdminDashboard /> : <section className="info-page"><div className="eyebrow">OPEN DATA, RESPONSIBLY</div><h1>情報透明，<span className="accent">蒐集有界線。</span></h1><p className="lead">Exam Radar 索引各校公開考試公告，讓分散的段考資訊更容易找到。</p><div className="info-grid"><article><ShieldCheck /><h3>只讀公開資訊</h3><p>遵守 robots.txt、網域頻率限制與 crawl-delay。不繞過登入、CAPTCHA 或權限限制。</p></article><article><ExternalLink /><h3>保留原始來源</h3><p>每份範圍保留原公告和修正紀錄。正式備考請核對學校最新公告；示範資料會明確標示。</p></article><article><Activity /><h3>定期檢查更新</h3><p>使用內容雜湊識別變更，保留文件原文與版本。需人工核對的抽取結果會先進入審核佇列。</p></article></div><div className="crawler-block"><h2>爬蟲與退出索引</h2><p>辨識名稱：<code>ExamRadarBot/1.0</code></p><p>校方可透過 robots.txt 禁止索引。管理員亦可於控制台停用學校爬取；專案聯絡方式請見 <a href="https://github.com/steventeng2022/Exam-radar" target="_blank" rel="noopener noreferrer">GitHub 專案</a>。</p><p>目前以高中公開 HTML、PDF、DOCX、XLSX 為主要解析格式，掃描式文件與特殊版面仍需人工核對。本平台為獨立專案，並非學校官方網站。</p></div></section>}</main><footer><a className="brand" href="/"><Radar size={21} />EXAM<span>RADAR</span></a><span>把分散資訊，變成準備的方向。</span><a href="/crawler/">資料來源與爬蟲政策</a><a href="/dashboard/">管理控制台</a><small>© {new Date().getFullYear()} Exam Radar</small></footer></>;
}
